person:
  userName: "张三"
  boss: false
  birth: 2021/02/25 10:53:00
  age: 19
  pet:
    name: "小明"
    weight: 34.34
  interests: ['唱','跳','rap','篮球']
  animal:
    - jerry
    - mario
  score:
    english:
          first: 30
          second: 40
          third: 50
    math: [131,140,148]
    chinese: {first: 128,second: 136}
  salarys: [3999,4999.98,5999.99]
  allPets:
    sick:
      - {name: tom}
      - {name: jerry,weight: 47}
    health: [{name: mario,weight: 47}]


